version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: runner-dev
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app/src
    environment:
      - NODE_ENV=development
    command: npm run dev
