version: "3.8"

services:
  app:
    build:
      context: .
    ports:
      - "80:80"
      - "443:443"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # gives access to the Docker deamon
      - /etc/letsencrypt/live/code-sprint-backend.khaftab.me:/etc/nginx/ssl:ro
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb+srv://username:password@cluster0.lgin6.mongodb.net/code-sprint
      - ORIGINS=http://localhost:5173,http://localhost:5174
      - CONTAINER_POOL_SIZE=1
    command: /bin/sh -c "/usr/src/app/setup.sh && node dist/server.js"
